/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'blog-posts': BlogPost;
    pages: Page;
    'case-results': CaseResult;
    locations: Location;
    'faq-items': FaqItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'case-results': CaseResultsSelect<false> | CaseResultsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    contact: Contact;
    'lawyer-profile': LawyerProfile;
    'social-links': SocialLink;
    'google-reviews': GoogleReview;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'lawyer-profile': LawyerProfileSelect<false> | LawyerProfileSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    'google-reviews': GoogleReviewsSelect<false> | GoogleReviewsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * People with access to this admin panel. Add colleagues here only if they should be able to edit the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'owner' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos, logos, and other files used across the site. Drag-drop to upload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines (e.g., 'Mandeep Saggi at the Brampton courthouse').
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Criminal defence practice areas. Each entry becomes a page at /services/<slug>. Reorder by dragging or by editing the Order field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * PASTE FROM CHATGPT / DOCS HERE — headings (##), bullets (-), numbered lists (1.), quotes (>), **bold**, *italic*, and [links](url) are auto-detected. On save, this replaces the Body below and this field clears itself. Leave empty to edit the Body directly.
   */
  markdownImport?: string | null;
  title: string;
  /**
   * URL segment — a single word or hyphenated phrase. E.g. 'impaired-driving-dui'. Slashes, spaces, and uppercase are auto-cleaned on save.
   */
  slug: string;
  /**
   * Single letter or glyph shown in the icon square (B, D, A, etc.).
   */
  icon: string;
  /**
   * Small label above the H1 (e.g., 'Impaired driving · Over 80 · Refusal').
   */
  heroKicker?: string | null;
  /**
   * One-paragraph lede shown under the H1. 200–350 chars.
   */
  summary: string;
  /**
   * Optional hero image. When empty, a branded visual is generated automatically.
   */
  heroImage?: (number | null) | Media;
  /**
   * Main article body. Use the toolbar to change block type (paragraph, H1–H6, quote, list) and apply inline formatting.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sort order in listings. Lower = appears first.
   */
  order?: number | null;
  /**
   * Used to auto-suggest related services on each service page.
   */
  category:
    'general' | 'impaired' | 'personal' | 'drugs' | 'weapons' | 'property' | 'financial' | 'sexual' | 'youth' | 'bail';
  /**
   * If enabled, this service is shown as related on EVERY other service page (use for Bail Hearings, Criminal Lawyer).
   */
  universal?: boolean | null;
  /**
   * Google search-result title. Leave blank to use the entry's title. 50–60 chars is ideal.
   */
  seoTitle?: string | null;
  /**
   * Meta description shown under the title in Google. Leave blank to use the entry's summary. 150–160 chars is ideal.
   */
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (e.g. "impaired driving, Brampton lawyer, over 80"). Optional.
   */
  keywords?: string | null;
  /**
   * Preview image shown when this page is shared on Facebook / LinkedIn / WhatsApp / X. Recommended: 1200 × 630. If empty, the entry's featured / hero image is used.
   */
  ogImage?: (number | null) | Media;
  /**
   * Optional social-share title. Leave blank to reuse the SEO title.
   */
  ogTitle?: string | null;
  /**
   * Optional social-share description. Leave blank to reuse the SEO description.
   */
  ogDescription?: string | null;
  /**
   * Only set this when this content lives at a different URL you want Google to prefer. Otherwise leave blank.
   */
  canonicalOverride?: string | null;
  /**
   * Hide this page from Google. Keep OFF unless you have a reason to hide it.
   */
  noindex?: boolean | null;
  /**
   * Tell search engines NOT to follow this page's links. Rarely needed — keep OFF.
   */
  nofollow?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Articles for the journal. Each becomes a page at /blog/<slug> and appears on related service pages automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * PASTE FROM CHATGPT / DOCS HERE — headings, bullets, numbered lists, quotes, and inline formatting are auto-detected. On save, this replaces the Body below and this field clears itself. Leave empty to edit the Body directly.
   */
  markdownImport?: string | null;
  title: string;
  /**
   * URL segment — a single word or hyphenated phrase. Slashes, spaces, and uppercase are auto-cleaned on save.
   */
  slug: string;
  /**
   * 1–2 sentence summary shown on cards and in search results. 150–250 chars.
   */
  excerpt: string;
  /**
   * Featured image — shown on the article card, on the hero at the top of the post, and as the default social-share image. Recommended: 1600 × 900 or larger.
   */
  cover?: (number | null) | Media;
  /**
   * Full article. Toolbar above lets you change block type (H1–H6, paragraph, quote, list) and apply formatting.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. 'Bail', 'Charter', 'Domestic', 'Sentencing'.
   */
  category: string;
  /**
   * Related practice areas. This post will appear on those service pages.
   */
  services?: (number | Service)[] | null;
  /**
   * Free-form tags (e.g., 'arrest', 'first-24-hours').
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. '6 min read'. Leave blank to omit.
   */
  readTime?: string | null;
  /**
   * Google search-result title. Leave blank to use the entry's title. 50–60 chars is ideal.
   */
  seoTitle?: string | null;
  /**
   * Meta description shown under the title in Google. Leave blank to use the entry's summary. 150–160 chars is ideal.
   */
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (e.g. "impaired driving, Brampton lawyer, over 80"). Optional.
   */
  keywords?: string | null;
  /**
   * Preview image shown when this page is shared on Facebook / LinkedIn / WhatsApp / X. Recommended: 1200 × 630. If empty, the entry's featured / hero image is used.
   */
  ogImage?: (number | null) | Media;
  /**
   * Optional social-share title. Leave blank to reuse the SEO title.
   */
  ogTitle?: string | null;
  /**
   * Optional social-share description. Leave blank to reuse the SEO description.
   */
  ogDescription?: string | null;
  /**
   * Only set this when this content lives at a different URL you want Google to prefer. Otherwise leave blank.
   */
  canonicalOverride?: string | null;
  /**
   * Hide this page from Google. Keep OFF unless you have a reason to hide it.
   */
  noindex?: boolean | null;
  /**
   * Tell search engines NOT to follow this page's links. Rarely needed — keep OFF.
   */
  nofollow?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Custom pages (Privacy Policy, Terms, Fees, Team, etc.). Each becomes a page at /<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * PASTE FROM CHATGPT / DOCS HERE — headings, bullets, numbered lists, quotes, and inline formatting are auto-detected. On save, this replaces the Body below and this field clears itself. Leave empty to edit the Body directly.
   */
  markdownImport?: string | null;
  title: string;
  /**
   * URL segment — a single word or hyphenated phrase. Slashes, spaces, and uppercase are auto-cleaned on save. Avoid these built-in slugs: services, blog, about, contact, booking, locations, admin, api.
   */
  slug: string;
  /**
   * Small label above the H1 (optional).
   */
  heroKicker?: string | null;
  /**
   * Paragraph shown under the H1 (optional).
   */
  summary?: string | null;
  /**
   * Featured / hero image shown at the top of the page and used as the default social-share image. Recommended: 1600 × 900 or larger.
   */
  heroImage?: (number | null) | Media;
  /**
   * Page content. Toolbar above lets you change block type (H1–H6, paragraph, quote, list) and apply formatting.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Google search-result title. Leave blank to use the entry's title. 50–60 chars is ideal.
   */
  seoTitle?: string | null;
  /**
   * Meta description shown under the title in Google. Leave blank to use the entry's summary. 150–160 chars is ideal.
   */
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (e.g. "impaired driving, Brampton lawyer, over 80"). Optional.
   */
  keywords?: string | null;
  /**
   * Preview image shown when this page is shared on Facebook / LinkedIn / WhatsApp / X. Recommended: 1200 × 630. If empty, the entry's featured / hero image is used.
   */
  ogImage?: (number | null) | Media;
  /**
   * Optional social-share title. Leave blank to reuse the SEO title.
   */
  ogTitle?: string | null;
  /**
   * Optional social-share description. Leave blank to reuse the SEO description.
   */
  ogDescription?: string | null;
  /**
   * Only set this when this content lives at a different URL you want Google to prefer. Otherwise leave blank.
   */
  canonicalOverride?: string | null;
  /**
   * Hide this page from Google. Keep OFF unless you have a reason to hide it.
   */
  noindex?: boolean | null;
  /**
   * Tell search engines NOT to follow this page's links. Rarely needed — keep OFF.
   */
  nofollow?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Verified case outcomes. Every entry is visible on the home page results section; entries also appear on their linked service pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-results".
 */
export interface CaseResult {
  id: number;
  /**
   * e.g. 'Over 80 (impaired driving)'.
   */
  charge: string;
  /**
   * Full outcome sentence. Wrap the key verb in <em>…</em> for visual emphasis, e.g. 'Charges <em>withdrawn</em> following Charter application.'
   */
  outcome: string;
  outcomeTag: 'withdrawn' | 'acquitted' | 'stayed' | 'reduced' | 'discharge' | 'peace-bond' | 'diverted' | 'released';
  outcomeLabel: string;
  /**
   * e.g. 'Brampton', 'Peel Region', 'Superior Court'.
   */
  jurisdiction?: string | null;
  /**
   * e.g. '2025'.
   */
  year?: string | null;
  /**
   * Which service pages this outcome should appear on (auto-filter).
   */
  services?: (number | Service)[] | null;
  /**
   * When enabled, a visible SAMPLE banner shows in the UI and this entry is treated as placeholder content. UNCHECK ONLY for verified, client-consented outcomes.
   */
  sample?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Communities the firm serves. 'Main' locations show as featured chips; 'Also' locations show in the extended list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  tier: 'main' | 'also';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently-asked questions shown on the home page and (optionally) on service pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  location?: ('home' | 'booking' | 'contact')[] | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'case-results';
        value: number | CaseResult;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  markdownImport?: T;
  title?: T;
  slug?: T;
  icon?: T;
  heroKicker?: T;
  summary?: T;
  heroImage?: T;
  body?: T;
  order?: T;
  category?: T;
  universal?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  ogTitle?: T;
  ogDescription?: T;
  canonicalOverride?: T;
  noindex?: T;
  nofollow?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  markdownImport?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  category?: T;
  services?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  readTime?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  ogTitle?: T;
  ogDescription?: T;
  canonicalOverride?: T;
  noindex?: T;
  nofollow?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  markdownImport?: T;
  title?: T;
  slug?: T;
  heroKicker?: T;
  summary?: T;
  heroImage?: T;
  body?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  ogTitle?: T;
  ogDescription?: T;
  canonicalOverride?: T;
  noindex?: T;
  nofollow?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-results_select".
 */
export interface CaseResultsSelect<T extends boolean = true> {
  charge?: T;
  outcome?: T;
  outcomeTag?: T;
  outcomeLabel?: T;
  jurisdiction?: T;
  year?: T;
  services?: T;
  sample?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tier?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  location?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide identity and defaults. Edit anything here and it updates across every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  legalName?: string | null;
  tagline?: string | null;
  description?: string | null;
  url?: string | null;
  /**
   * Image shown when the site is shared on social media (1200×630).
   */
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phone, email, address, hours, and booking link. Used everywhere across the site — change it once, updates everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * Displayed as-is. E.g. '647-983-6720'.
   */
  phone: string;
  /**
   * Click-to-call URL. Include country code. E.g. 'tel:+16479836720'.
   */
  phoneHref: string;
  /**
   * Primary contact email — receives all form submissions and appears across the site.
   */
  email: string;
  address?: {
    street?: string | null;
    city?: string | null;
    province?: string | null;
    postal?: string | null;
    country?: string | null;
  };
  /**
   * Free-form hours line. E.g. 'Mon–Fri 9am–6pm · 24/7 emergency line'.
   */
  hours?: string | null;
  /**
   * Where 'Book Consultation' buttons point. Use '/booking' for the built-in form, or paste a Calendly / external URL.
   */
  bookingUrl?: string | null;
  /**
   * Full Google Maps link to the office.
   */
  mapsUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Mandeep Saggi's profile — photo, bio, credentials, award. Used on the Meet the Lawyer section and the /about page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyer-profile".
 */
export interface LawyerProfile {
  id: number;
  name: string;
  title?: string | null;
  role?: string | null;
  /**
   * Portrait photo. Portrait aspect (4:5 or similar) works best.
   */
  photo?: (number | null) | Media;
  tagline?: string | null;
  /**
   * Short quote / lede shown prominently under the name (1–2 sentences).
   */
  bio?: string | null;
  /**
   * Longer bio shown on the /about page.
   */
  bioLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Degrees, admissions, memberships, languages.
   */
  credentials?:
    | {
        title: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Recognition line shown as a highlighted badge.
   */
  award?: string | null;
  languages?:
    | {
        language?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Where 'Learn More About the Lawyer' links to.
   */
  profileUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Social profile URLs shown in the footer. Leave blank to hide an icon.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  facebook?: string | null;
  youtube?: string | null;
  twitter?: string | null;
  linkedin?: string | null;
  instagram?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * How the Client Reviews section pulls data. Trustindex embed takes priority, then Places API (Place ID), then a plain 'See on Google' link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-reviews".
 */
export interface GoogleReview {
  id: number;
  /**
   * Trustindex or Elfsight <script> embed. Highest priority — when set, this widget renders directly.
   */
  widgetEmbed?: string | null;
  /**
   * Google Business Profile Place ID (starts with ChIJ…). Used by the Places-API path when the widget is not set.
   */
  placeId?: string | null;
  /**
   * Public share link to the GMB profile. Used for the 'See reviews on Google' CTA.
   */
  reviewsUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The site logo, header, and footer link lists. Upload a new logo and it appears in the top nav and the footer automatically. Add / remove / reorder to change what appears in the site nav.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Uploaded here → shown in the top navigation bar AND the footer. Ideally a transparent PNG or SVG, roughly 3:1 or wider, at least 400 px tall. Leave empty to fall back to the built-in /logo.png.
   */
  logo?: (number | null) | Media;
  /**
   * Read aloud by screen readers and used by Google when the logo image cannot load. Keep it short and descriptive.
   */
  logoAlt?: string | null;
  /**
   * Shown in the top navigation bar.
   */
  header?:
    | {
        label: string;
        /**
         * e.g. /services or https://…
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footerPractice?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerFirm?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  description?: T;
  url?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  phone?: T;
  phoneHref?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        province?: T;
        postal?: T;
        country?: T;
      };
  hours?: T;
  bookingUrl?: T;
  mapsUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyer-profile_select".
 */
export interface LawyerProfileSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  role?: T;
  photo?: T;
  tagline?: T;
  bio?: T;
  bioLong?: T;
  credentials?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  award?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  profileUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  facebook?: T;
  youtube?: T;
  twitter?: T;
  linkedin?: T;
  instagram?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-reviews_select".
 */
export interface GoogleReviewsSelect<T extends boolean = true> {
  widgetEmbed?: T;
  placeId?: T;
  reviewsUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  logoAlt?: T;
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerPractice?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerFirm?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}